site_name: My Learning
# site_url:

nav:
  - Home: index.md
  - About: about.md
  - Learning:
    - Red Hat: 
      - RH199: 'redhat/01-RH199/01-RH199.md'
      - RH294: 'redhat/02-RH294/02-RH294.md'
    - FinOps Practitioner:
      - FinOps Certified Practitioner Introduction : 'finops/01_Introduction_finops.md'
      - Cloud Changes IT: 'finops/02_cloud_changes_it.md'
      - What is FinOps: 'finops/03_what_is_FinOps.md'
      - FinOps Framework & Principles: 'finops/04_FinOps_framework_&_principles.md'
      - Personas & Teams: 'finops/05_personas_&_teams.md'
      - Domains & Capabilities: 'finops/06_domains_&_capabilities.md'
      - Motivations & Common Language: 'finops/07_Motivations_&_Common_Language.md'
      - Anatomy of a Cloud Bill: 'finops/08_Anatomy_of_a_Cloud_Bill.md'
      - FOCUS: 'finops/09_FOCUS.md'
      - Running the FinOps Team: 'finops/10_Running_the_FinOps_Team.md'
      - FOCP: 'finops/focp_questions.md'
    - Cisco Networking Academy:
      - Fundamentos de Python 1: 'cisco/fundamentos_python_1.md'
theme:
  name: readthedocs
  highlightjs: true
  locale: en

