site_name: My Learning
# site_url:

nav:
  - Home: index.md
  - About: about.md
  - Learning:
    - Red Hat: 
      - RH199: 'redhat/01-RH199/01-RH199.md'
      - RH294: 'redhat/02-RH294/02-RH294.md'
    - FinOps Practitioner:
      - FinOps Certified Practitioner Introduction : 'finops/01_Introduction_finops.md'
      - Cloud Changes IT: 'finops/02_cloud_changes_it.md'
      - What is FinOps: 'finops/03_what_is_FinOps.md'
      - FOCP: 'finops/focp_questions.md'
    - Cisco Networking Academy:
      - Fundamentos de Python 1: 'cisco/fundamentos_python_1.md'
theme: readthedocs

