site_name: My Learning
# site_url:

nav:
  - Home: home.md
  - Planning: planning.md
  - Red Hat:
    - Notas Red Hat: '01_redhat/notes_redhat.md' 
    - 01 RHCSA Rapid Track (RH199):
      - Objetivos RH199: '01_redhat/01-RH199/01-EX200_RHCSA.md'
      - Capítulo 1, Sistema de accesos y soporte: '01_redhat/01-RH199/01-RH199_C1.md'
      - Capítulo 2, Gestión de Archivos desde CmdLine: '01_redhat/01-RH199/01-RH199_C2.md'
      - Capítulo 3, Gestión de usuarios y grupos locales: '01_redhat/01-RH199/01-RH199_C3.md'
      - Capítulo 4, Control de acceso a archivos: '01_redhat/01-RH199/01-RH199_C4.md'
      - Capítulo 5, Gestión de seguridad SELinux: '01_redhat/01-RH199/01-RH199_C5.md'
      - Capítulo 6, Ajustes de rendimiento del sistema: '01_redhat/01-RH199/01-RH199_C6.md'
      - Capítulo 7, Programación de tareas: '01_redhat/01-RH199/01-RH199_C7.md'
      - Capítulo 8, Instalación y actualización de paquetes de software: '01_redhat/01-RH199/01-RH199_C8.md'
      - Capítulo 9, Gestión básica de almacenamiento (Storage): '01_redhat/01-RH199/01-RH199_C9.md'
      - Capítulo 10, Gestión de almacenamiento lógico (Stack) : '01_redhat/01-RH199/01-RH199_C10.md'
      - Capítulo 11, Servicios de control y procesos de boot: '01_redhat/01-RH199/01-RH199_C11.md'
      - Capítulo 12, Análisis y almacenamiento de Logs: '01_redhat/01-RH199/01-RH199_C12.md'
      - Capítulo 13, Gestión de redes (Networking): '01_redhat/01-RH199/01-RH199_C13.md'
      - Capítulo 14, Acceso de almacenamiento por red (Network-Attached): '01_redhat/01-RH199/01-RH199_C14.md'
      - Capítulo 15, Gestión de seguridad de redes: '01_redhat/01-RH199/01-RH199_C15.md'
      - Capítulo 16, Ejecución de contenedores: '01_redhat/01-RH199/01-RH199_C16.md'
      - Red Hat Enterprise Linux 9.0: '01_redhat/01-RH199/02-RH199.md'
      - Notas de práctica: '01_redhat/01-RH199/03-RH199_notes.md'
    - 02 RHEL Automation with Ansible (RH294): 
      - Red Hat Enterprise Linux Automation with Ansible: '01_redhat/02-RH294/01-RH294.md'
      - Capítulo 1, Introducción Ansible: '01_redhat/02-RH294/02-RH294_C1.md'
      - Capítulo 2, Implementación de Ansible Playbook: '01_redhat/02-RH294/02-RH294_C2.md'
      - Capítulo 3, Gestión de variables y facts: '01_redhat/02-RH294/02-RH294_C3.md'
      - Capítulo 4, Implementación de tareas de control: '01_redhat/02-RH294/02-RH294_C4.md'
      - Capítulo 5, Despliegue de archivos en Hosts gestionados: '01_redhat/02-RH294/02-RH294_C5.md'
      - Capítulo 6, Gestión de Play y Playbook complejos: '01_redhat/02-RH294/02-RH294_C6.md'
      - Capítulo 7, Simplificando Playbook's con roles y contenido de Colecciones (Collections): '01_redhat/02-RH294/02-RH294_C7.md'
      - Capítulo 8, Troubleshooting: '01_redhat/02-RH294/02-RH294_C8.md'
      - Capítulo 9, Automatización de tareas de Administración Linux: '01_redhat/02-RH294/02-RH294_C9.md'
      - Notas de práctica: '01_redhat/02-RH294/02-RHELAA_notes.md'
      - Ejecicio de práctica, playbooks: '01_redhat/02-RH294/02-RH294_playbooks.md'
    - 03 Managing Enterprise Automation with RH AAP (DO467):
      - Managing Enterprise Automation with Red Hat Ansible Automation Platform: '01_redhat/03-DO467/01-DO467.md'
      - Capítulo 1, Instalación de Red Hat Ansible Automation Platform: '01_redhat/03-DO467/03-DO467_C1.md'
      - Capítulo 2, Gestión de acceso de usuarios: '01_redhat/03-DO467/03-DO467_C2.md'
      - Capítulo 3, Gestión de inventarios y credenciales de máquinas: '01_redhat/03-DO467/03-DO467_C3.md'
      - Capítulo 4, Gestión de Proyectos y ejecución Jobs: '01_redhat/03-DO467/03-DO467_C4.md'
      - Capítulo 5, Configuración avanzada de Jobs: '01_redhat/03-DO467/03-DO467_C5.md'
      - Capítulo 6, Construyendo Job worflows : '01_redhat/03-DO467/03-DO467_C6.md'
      - Capítulo 7, Gestión Vanzada de inventarios: '01_redhat/03-DO467/03-DO467_C7.md'
      - Capítulo 8, Automatizando configuración de AAP: '01_redhat/03-DO467/03-DO467_C8.md'
      - Capítulo 9, Mantenimiento de AAP: '01_redhat/03-DO467/03-DO467_C9.md'
      - Capítulo 10, Obteniendo información desde Red Hat Insights: '01_redhat/03-DO467/03-DO467_C10.md'
      - Capítulo 11, Construyendo implementación a gran escala de AAP: '01_redhat/03-DO467/03-DO467_C11.md'
      - Notas de práctica: '01_redhat/03-DO467/RHAAP_notes.md'
    - 04 Developing Advanced Automation with RH AAP (DO374):
      - Capítulo 1, Desarrollando Playbook con AAP 2: '01_redhat/04-DO374/04-DO374_C1.md'
      - Capítulo 2, Gestión de contenido de Colecciones y Entornos de Ejecución (Collection & EE): '01_redhat/04-DO374/04-DO374_C2.md'
      - Capítulo 3, Ejecutando Playbooks con el Automation Controller: '01_redhat/04-DO374/04-DO374_C3.md'
      - Capítulo 4, Trabajando con ajustes de configuraciones de Ansible: '01_redhat/04-DO374/04-DO374_C4.md'
      - Capítulo 5, Gestión de Inventarios: '01_redhat/04-DO374/04-DO374_C5.md'
      - Capítulo 6, Gestión de Tareas de Ejecución : '01_redhat/04-DO374/04-DO374_C6.md'
      - Capítulo 7, Transformando data con Filtros y Plug-ins: '01_redhat/04-DO374/04-DO374_C7.md'
      - Capítulo 8, Coordinando las actualizaciones: '01_redhat/04-DO374/04-DO374_C8.md'
      - Capítulo 9, Creando Colecciones y Ambientes de Ejecución (Collections & EE): '01_redhat/04-DO374/04-DO374_C9.md'
      - Notas de práctica: '01_redhat/04-DO374/RHAAP_notes.md'
      - Prácticas: 
        - Práctica Colecciones: '01_redhat/04-DO374/practice_collections.md'
    - 05 Red Hat Satellite 6 Administration (RH403): 
      - Install & Manage Red Hat Satellite: '01_redhat/05-RHSA6/01-RHSA6.md'
      - Capítulo 1, Planeación y despliegue de Red Hat Satellite: '01_redhat/05-RHSA6/05-RH403_C1.md'
      - Capítulo 2, Gestión de ciclos de vida de Software (Lifecycles): '01_redhat/05-RHSA6/05-RH403_C2.md'
      - Capítulo 3, Registro de hosts: '01_redhat/05-RHSA6/05-RH403_C3.md'
      - Capítulo 4, Despliegue de Software en Hosts: '01_redhat/05-RHSA6/05-RH403_C4.md'
      - Capítulo 5, Despliegue de Software Personalizado: '01_redhat/05-RHSA6/05-RH403_C5.md'
      - Capítulo 6, Despliegue de Servidores Capsula Satellite : '01_redhat/05-RHSA6/05-RH403_C6.md'
      - Capítulo 7, Ejecución Remota: '01_redhat/05-RHSA6/05-RH403_C7.md'
      - Capítulo 8, Preparar recursos de Red para aprovisionamiento de Hosts: '01_redhat/05-RHSA6/05-RH403_C8.md'
      - Capítulo 9, Aprovisionamiento de contenido de Hosts: '01_redhat/05-RHSA6/05-RH403_C9.md'
      - Capítulo 10, Automatizar Gestión de Red Hat Satellite: '01_redhat/05-RHSA6/05-RH403_C10.md'
      - Capítulo 11, Mantenimiento de Red Hat Satellite: '01_redhat/05-RHSA6/05-RH403_C11.md'
      - Capítulo 12, Integrar Red Hat Satellite con plataformas híbridas Cloud: '01_redhat/05-RHSA6/05-RH403_C12.md'
      - Notas de práctica: '01_redhat/05-RHSA6/RH403_notes.md'
      - Pre-requisitos: '01_redhat/05-RHSA6/RH403_prereq.md'
    - 06 Red Hat OpenShift Administration I (DO180): 
      - Operating a Production Cluster: '01_redhat/06-DO180/01-DO180.md'
      - Capítulo 1, Introducción a Kubernetes y Openshift: '01_redhat/06-DO180/06-DO180_C1.md'
      - Capítulo 2, Linea de comandos Kubernetes y Openshift, Interfaces y APIs: '01_redhat/06-DO180/06-DO180_C2.md'
      - Capítulo 3, Ejecución de aplicaciones como Contenedores y Pods: '01_redhat/06-DO180/06-DO180_C3.md'
      - Capítulo 4, Gestión de despliegue y aplicaciones en red sobre Kubernetes: '01_redhat/06-DO180/06-DO180_C4.md'
      - Capítulo 5, Gestión de almacenamiento (Storage) para configuración de aplicación y Data : '01_redhat/06-DO180/06-DO180_C5.md'
      - Capítulo 6, Configuración de Aplicaciones con disponibilidad : '01_redhat/06-DO180/06-DO180_C6.md'
      - Capítulo 7, Gestión de actualizaciones de Aplicaciones: '01_redhat/06-DO180/06-DO180_C7.md'
      - Notas de práctica: '01_redhat/06-DO180/DO180_notes.md'
    - 07 Red Hat OpenShift Administration II (DO280):
      - Capítulo 1, Gestión Declarativa de recursos: '01_redhat/07-DO280/07-DO280_C1.md'
      - Capítulo 2, Despliegue de aplicaciones empaquetadas: '01_redhat/07-DO280/07-DO280_C2.md'
      - Capítulo 3, Auntenticación y Autorización: '01_redhat/07-DO280/07-DO280_C3.md'
      - Capítulo 4, Seguridad de Redes: '01_redhat/07-DO280/07-DO280_C4.md'
      - Capítulo 5, Exponer apps no HTTP/SNI: '01_redhat/07-DO280/07-DO280_C5.md'
      - Capítulo 6, Habilitar Auto-servicio de Desarrollo: '01_redhat/07-DO280/07-DO280_C6.md'
      - Capítulo 7, Gestión de operadores de Kubernetes: '01_redhat/07-DO280/07-DO280_C7.md'
      - Capítulo 8, Seguridad de apllicaciones: '01_redhat/07-DO280/07-DO280_C8.md'
      - Capítulo 9, Actualizaciones de Openshift: '01_redhat/07-DO280/07-DO280_C9.md'
      - Notas de práctica: '01_redhat/07-DO280/DO280_notes.md'
    - 08 Red Hat Openshift Installation (DO322):
      - Capitulo 1, Descripción del proceso de Instalación de OCP: '01_redhat/08-DO322/08-DO322_C1.md'
      - Capitulo 2, Ejecutando la instalación de OCP: '01_redhat/08-DO322/08-DO322_C2.md'
  - FinOps Foundation:
    - FinOps Certified Practitioner : '02_finops/01_finops_practitioner.md'
    - FOCP: '02_finops/focp_questions.md'
  - Cisco Networking Academy:
    - Fundamentos de Python 1: '03_cisco/fundamentos_python_1.md'
  - English (Smart Online): 
    - A1: '04_english/A1.md'
  - About: about.md
    
theme:
  name: material
  logo: logo.png
  palette:
    primary: light green
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  #name: readthedocs
  #highlightjs: true
  #locale: en

markdown_extensions:
  - attr_list
  



