site_name: My Learning
# site_url:

nav:
  - Home: home.md
  - Index: index.md
  - About: about.md
  - Planning: planning.md
  - Red Hat: 
    - 01 RHCSA Rapid Track (RH199):
      - Objetivos RH199: '01_redhat/01-RH199/01-EX200_RHCSA.md'
      - Red Hat Enterprise Linux 9.0: '01_redhat/01-RH199/02-RH199.md'
      - Notas de práctica: '01_redhat/01-RH199/03-RH199_notes.md'
    - 02 RHEL Automation with Ansible (RH294): 
      - Red Hat Enterprise Linux Automation with Ansible: '01_redhat/02-RH294/01-RH294.md'
      - Notas de práctica: '01_redhat/02-RH294/02-RHELAA_notes.md'
    - 03 Managing Enterprimse Automation with RH AAP (DO467):
      - Managing Enterprise Automation with Red Hat Ansible Automation Platform: '01_redhat/03-DO467/01-DO467.md' 
      - Notas de práctica: '01_redhat/03-DO467/RHAAP_notes.md'
    - 04 Developing Advanced Automation with RH AAP (DO374):
      - Prácticas: 
        - Práctica Norlan: '01_redhat/04-DO374/practice_norlan.md'
    - 05 Red Hat Satellite 6 Administration (RH403): '01_redhat/05-RHSA6/01-RHSA6.md'
    - 06 Red Hat OpenShift Administration I (DO180): 
      - Operating a Production Cluster: '01_redhat/06-DO180/01-DO180.md'
      - Notas de práctica: '01_redhat/06-DO180/DO180_notes.md'
  - FinOps Foundation:
    - FinOps Certified Practitioner : '02_finops/01_finops_practitioner.md'
    - FOCP: '02_finops/focp_questions.md'
  - Cisco Networking Academy:
    - Fundamentos de Python 1: '03_cisco/fundamentos_python_1.md'
  - English (Smart Online): 
    - A1: '04_english/A1.md'
    
theme:
  name: material
  logo: logo.png
  palette:
    primary: light green
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  #name: readthedocs
  #highlightjs: true
  #locale: en

markdown_extensions:
  - attr_list
  



