---
- name: Validate URL's
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    validate_aap: false
    validate_rhs: true
  vars_files:
    - vars/urls.yml
  
  tasks:
    - name: Test URL AAP
      ansible.builtin.uri:
        url: '{{ item }}'
        validate_certs: false
        status_code: [200, 403]
      loop:
        - https://registry.redhat.io
        - http://registry.redhat.io
        - https://automation-hub-prd.s3.amazonaws.com
        - https://automation-hub-prd.s3.us-east-2.amazonaws.com/
        - https://ansible-galaxy-ng.s3.dualstack.us-east-1.amazonaws.com
        - https://access.redhat.com
        - https://subscription.rhsm.redhat.com 
        - https://subscription.rhn.redhat.com 
        - https://cdn.redhat.com
        - https://console.redhat.com 
        - https://api.access.redhat.com 
        - https://cert-api.access.redhat.com 
        - https://sso.redhat.com
        - https://galaxy.ansible.com
        - https://cert.console.redhat.com
        - https://catalog.redhat.com
        - http://cdn.quay.io
        - https://cdn.quay.io
        - http://cdn01.quay.io
        - https://cdn01.quay.io
        - http://cdn02.quay.io
        - https://cdn02.quay.io
        - http://cdn03.quay.io
        - https://cdn03.quay.io
#        - *.akamaiedge.net
#        - *.akamaitechnologies.com
      when: validate_aap == true

    - name: Test URL RHS
      ansible.builtin.uri:
        url: '{{ item }}'
        validate_certs: false
        status_code: [200, 403]
      loop:
        - https://subscription.rhn.redhat.com
        - https://subscription.rhsm.redhat.com
        - https://cdn.redhat.com
        - https://cert-api.access.redhat.com
        - https://api.access.redhat.com
#        - https://*.akamaiedge.net
#        - https://*.akamaitechnologies.com
      when: validate_rhs == true 