---
name: Make users
hosts: all
gather_facts: false
become: true
vars: 
  useradd: ansible

tasks:
  - name: Create user
    ansible.builtin.user:
      name: '{{ useradd }}'
      comment=: 'Ansible Service User Account'
      state: present
      password: $1$mysecretpass$1
      update_password: on_create

  - name: Permisions sudoers
    ansible.builtin.copy:
      dest: /etc/sudoers.d/{{ useradd }}-service-account
      content: '{{ useradd }} ALL=(ALL) NOPASSWD:ALL'
      mode: u=rw,g=r,o=r
      owner: root

  - name: Ensure key is in root's ~/.ssh/authorized_hosts
    ansible.posix.authorized_key:
      user: root
      state: present
      key: '{{ item }}'
    with_file:
      - ~/.ssh/id_rsa.pub